name: 💅 Hermegås 💅
on:
  pull_request
jobs: 
 comment:
    runs-on: ubuntu-latest
    permissions:
        contents: read 
        pull-requests: write  
    name: Hermegås
    steps:
      - name: goosy
        uses: henriettelienrebnor/Fagdag@write_to_file
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          PR_NUMBER: ${{ github.event.number }}