name: Haiku
on:
  pull_request
jobs: 
 comment:
    runs-on: ubuntu-latest
    permissions:
        contents: write 
        pull-requests: write  
    name: Hermegås
    steps:
      - name: goosy
        uses: henriettelienrebnor/Fagdag@main
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          PR_NUMBER: ${{ github.event.number }}